version: "3.9"

services:
  idp:
    image: floify-saml-idp:latest
    container_name: idp.blue.test
    ports:
      - "9080:9080"
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/sample-idp/saml/idp/metadata"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s

  sp:
    image: floify-test-sp:latest
    container_name: sp.blue.test
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - idp
